-- Ensure database exists and switch to it
IF DB_ID('MuTraProDB') IS NULL
BEGIN
  CREATE DATABASE MuTraProDB;
END
GO
USE MuTraProDB;
GO
IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL DROP TABLE dbo.Users;
IF OBJECT_ID('dbo.Roles', 'U') IS NOT NULL DROP TABLE dbo.Roles;
IF OBJECT_ID('dbo.Services', 'U') IS NOT NULL DROP TABLE dbo.Services;
IF OBJECT_ID('dbo.Requests', 'U') IS NOT NULL DROP TABLE dbo.Requests;
IF OBJECT_ID('dbo.RequestAssignees', 'U') IS NOT NULL DROP TABLE dbo.RequestAssignees;
IF OBJECT_ID('dbo.StudioRooms', 'U') IS NOT NULL DROP TABLE dbo.StudioRooms;
IF OBJECT_ID('dbo.Bookings', 'U') IS NOT NULL DROP TABLE dbo.Bookings;
IF OBJECT_ID('dbo.Files', 'U') IS NOT NULL DROP TABLE dbo.Files;
IF OBJECT_ID('dbo.Notifications', 'U') IS NOT NULL DROP TABLE dbo.Notifications;

CREATE TABLE dbo.Roles(
  RoleId INT IDENTITY PRIMARY KEY,
  Code NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE dbo.Users(
  UserId INT IDENTITY PRIMARY KEY,
  FullName NVARCHAR(120) NOT NULL,
  Email NVARCHAR(120) UNIQUE NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  RoleId INT NOT NULL FOREIGN KEY REFERENCES dbo.Roles(RoleId),
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Services(
  ServiceId INT IDENTITY PRIMARY KEY,
  Code NVARCHAR(50) UNIQUE NOT NULL,
  DisplayName NVARCHAR(120) NOT NULL
);

CREATE TABLE dbo.Requests(
  RequestId INT IDENTITY PRIMARY KEY,
  CustomerId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
  ServiceId INT NOT NULL FOREIGN KEY REFERENCES dbo.Services(ServiceId),
  Title NVARCHAR(200) NOT NULL,
  Detail NVARCHAR(MAX) NULL,
  Priority TINYINT NOT NULL DEFAULT 2,
  Status NVARCHAR(30) NOT NULL DEFAULT 'NEW',
  InputFileId INT NULL,
  OutputFileId INT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL
);

CREATE TABLE dbo.RequestAssignees(
  Id INT IDENTITY PRIMARY KEY,
  RequestId INT NOT NULL FOREIGN KEY REFERENCES dbo.Requests(RequestId),
  ExpertId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
  RoleCode NVARCHAR(50) NOT NULL,
  AssignedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.StudioRooms(
  RoomId INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(80) NOT NULL,
  Location NVARCHAR(200) NULL,
  Capacity INT NOT NULL DEFAULT 1,
  IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.Bookings(
  BookingId INT IDENTITY PRIMARY KEY,
  RoomId INT NOT NULL FOREIGN KEY REFERENCES dbo.StudioRooms(RoomId),
  RequestId INT NULL FOREIGN KEY REFERENCES dbo.Requests(RequestId),
  StartAt DATETIME2 NOT NULL,
  EndAt DATETIME2 NOT NULL,
  CreatedBy INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId)
);

CREATE TABLE dbo.Files(
  FileId INT IDENTITY PRIMARY KEY,
  OwnerId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
  FileName NVARCHAR(255) NOT NULL,
  FileUrl NVARCHAR(500) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Notifications(
  NotificationId INT IDENTITY PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(UserId),
  Message NVARCHAR(500) NOT NULL,
  IsRead BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

INSERT INTO dbo.Roles(Code) VALUES
('CUSTOMER'),('TRANSCRIBER'),('MIXER'),('ARTIST'),('STUDIO_ADMIN'),('ADMIN');

INSERT INTO dbo.Services(Code, DisplayName) VALUES
('TRANSCRIPTION','Phiên âm'),
('MIXING','Hòa âm'),
('RECORDING','Thu âm');

INSERT INTO dbo.StudioRooms(Name, Location, Capacity, IsActive) VALUES
('Room A','1st Floor',2,1),('Room B','2nd Floor',3,1);
