services:
  mysql:
    image: mysql:8.0
    container_name: mp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    ports: ["3307:3306"]
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpwd || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./services/auth-service
    environment:
      PORT: 5001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mutrapro_auth
      DB_USER: root
      DB_PASSWORD: rootpwd
      JWT_SECRET: "change_me_please"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["5001:5001"]

  order-service:
    build: ./services/order-service
    environment:
      PORT: 5002
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mutrapro_order
      DB_USER: root
      DB_PASSWORD: rootpwd
      JWT_SECRET: "change_me_please"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["5002:5002"]

  task-service:
    build: ./services/task-service
    environment:
      PORT: 5003
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mutrapro_task
      DB_USER: root
      DB_PASSWORD: rootpwd
      JWT_SECRET: "change_me_please"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["5003:5003"]

  file-service:
    build: ./services/file-service
    environment:
      PORT: 5004
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mutrapro_file
      DB_USER: root
      DB_PASSWORD: rootpwd
      JWT_SECRET: "change_me_please"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["5004:5004"]

  studio-service:
    build: ./services/studio-service
    environment:
      PORT: 5005
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mutrapro_studio
      DB_USER: root
      DB_PASSWORD: rootpwd
      JWT_SECRET: "change_me_please"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["5005:5005"]

  notification-service:
    build: ./services/notification-service
    environment:
      PORT: 5006
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mutrapro_notification
      DB_USER: root
      DB_PASSWORD: rootpwd
      JWT_SECRET: "change_me_please"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["5006:5006"]

  gateway:
    build: ./gateway
    environment:
      PORT: 4000
      AUTH_URL: http://auth-service:5001
      ORDER_URL: http://order-service:5002
      TASK_URL: http://task-service:5003
      FILE_URL: http://file-service:5004
      STUDIO_URL: http://studio-service:5005
      NOTI_URL: http://notification-service:5006
    depends_on:
      - auth-service
      - order-service
      - task-service
      - file-service
      - studio-service
      - notification-service
    ports: ["4000:4000"]

  web:
    build: ./web
    depends_on:
      - gateway
    ports: ["5173:80"]
