version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mutrapro_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: MuTraProDB
      MYSQL_USER: mutrapro
      MYSQL_PASSWORD: mutrapro_pwd
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pmutrapro_pwd || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: mutrapro_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 4000
      JWT_SECRET: "change_me_please"
      DB_SERVER: "db"
      DB_DATABASE: "MuTraProDB"
      DB_USER: "mutrapro"
      DB_PASSWORD: "mutrapro_pwd"
      DB_PORT: 3306
    ports:
      - "4000:4000"
