import { Router } from 'express';
import { authRequired } from '../../middleware/authRequired.js';
import * as c from './requests.controller.js';
const r = Router();
r.post('/', authRequired, c.createRequest);
r.get('/', authRequired, c.listRequests);
r.post('/:id/assign', authRequired, c.assignExperts);
r.post('/:id/status', authRequired, c.updateStatus);
r.get('/:id', authRequired, c.getDetail);
export default r;
