version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mutrapro_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: mutrapro_api
    depends_on:
      - db
    environment:
      PORT: 4000
      JWT_SECRET: "change_me_please"
      DB_SERVER: "db"
      DB_DATABASE: "master"           # init script will CREATE + USE MuTraProDB
      DB_USER: "sa"
      DB_PASSWORD: "YourStrong!Passw0rd"
      DB_PORT: 1433
      DB_ENCRYPT: "false"
      DB_TRUST_SERVER_CERTIFICATE: "true"
    ports:
      - "4000:4000"
