import express from 'express'; import cors from 'cors'; import morgan from 'morgan'; import dotenv from 'dotenv'; import mysql from 'mysql2/promise';
import { authRequired } from './middleware.js'; dotenv.config();
const app=express(); app.use(cors()); app.use(express.json()); app.use(morgan('dev'));
const pool=await mysql.createPool({host:process.env.DB_HOST,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,port:Number(process.env.DB_PORT||3306)});
app.get('/',(req,res)=>res.json({ok:true,service:'notification'}));
app.post('/notify',authRequired,async(req,res,n)=>{try{const {user_id,title,message,channel}=req.body;
  const [r]=await pool.execute('INSERT INTO notifications(user_id,title,message,channel,status) VALUES(?,?,?,?, "pending")',[user_id,title,message,channel||'system']);
  res.json({id:r.insertId});}catch(e){n(e)}});
app.get('/my',authRequired,async(req,res,n)=>{try{const [rows]=await pool.execute('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC',[req.user.uid]); res.json(rows);}catch(e){n(e)}});
app.use((e,req,res,n)=>{console.error(e); res.status(500).json({error:e.message})}); app.listen(process.env.PORT,()=>console.log('notification on',process.env.PORT));
